import{a as l,S as g,i as m}from"./assets/vendor-2e2a4521.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const f="https://api.thecatapi.com/v1",y="/breeds",v="/images/search",L="live_0MLgLm3ygusJhuSn6RvDBclcWVtxZS27hFvL1qegdoBmEHHqkWml5GyhzLGFd5H8";l.defaults.headers.common["x-api-key"]=L;const b=async()=>{const t=await l.get(`${f}${y}`);if(!t||t.status!==200)throw new Error("Failed to fetch cat breeds");return t.data},S=async t=>{const s=await l.get(`${f}${v}?breed_ids=${t}`);if(!s||s.status!==200)throw new Error("Error fetching cat by breed");return s.data},n=document.querySelector(".cat-info"),d=document.querySelector("#selectElement"),i=document.querySelector(".loader"),h=document.querySelector(".error"),u=new g({select:"#selectElement",settings:{placeholderText:"Search cats beeds"}});b().then(t=>{const s=[{value:"",text:u.settings.placeholderText,placeholder:!0},...t.map(({name:r,id:c})=>({value:`${c}`,text:`${r}`}))];u.setData(s),d.classList.remove("visually-hidden"),i.classList.add("visually-hidden"),d.addEventListener("change",E)}).catch(t=>{i.classList.add("visually-hidden"),h.classList.remove("visually-hidden"),m.show({message:"Failed to fetch cat breeds",messageColor:"red",messageSize:"18px",backgroundColor:"#ffffff",position:"topRight",timeout:2500}),console.log(t.message)});function E(t){const s=t.target.value;i.classList.remove("visually-hidden"),n.classList.add("visually-hidden"),S(s).then(r=>{console.log("FetchCatByBreed Response:",r),$(r)}).catch(r=>{n.innerHTML="",i.classList.add("visually-hidden"),h.classList.remove("visually-hidden"),m.show({message:"Error fetching cat by breed",messageColor:"red",messageSize:"18px",backgroundColor:"#ffffff",position:"topRight",timeout:2500}),console.log(r.message)}).finally(()=>{i.classList.add("visually-hidden"),n.classList.remove("visually-hidden")})}function $(t){const{url:s,breeds:r}=t[0],{name:c,alt_names:e,description:o,temperament:a}=r[0],p=`
  <div class="imgWrapper">
<img class="image" src="${s}" alt="${e}"/>
  </div>
  <div class="infoWrapper">
    <h2 class='title'>${c}</h2>
    <p class='description'>${o}</p>
    <h3 class='title subtitle'>Temperament</h3>
    <p class='temperament'>${a}</p>
  </div>
  `;n.innerHTML=p}
//# sourceMappingURL=commonHelpers.js.map
